implement book suggestions controller specs
wolox-training/sd-rails pull request #16
Opened 2019-03-12 13:46 UTC by sebasdeldi

## Summary

- Implements specs for book suggestions controller.
- Changes status code when validation fails.
## Trello Card

https://trello.com/c/agCpSsR5/27-crear-test-para-endpoint-de-creaci%C3%B3n-de-un-booksuggestion

2019-03-12 13:55 UTC, nicozar95 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +      it 'responds with 201 status' do
it 'responds with created status'

2019-03-12 13:56 UTC, nicozar95 requested changes
Great job, really small changes 💪

2019-03-12 13:56 UTC, nicozar95 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +      it 'responds with 422 status' do
it 'responds with unprocessable_entity status'

2019-03-12 13:56 UTC, nicozar95 commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +      it 'responds with 201 status' do
It 'responds with created status'

2019-03-12 13:59 UTC, Gmarn reviewed
I thing you miss one `context` : "When request params are invalid" and return 400

2019-03-12 13:59 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        post :create, params: { book_suggestion: book_suggestion }
Can we try to put the `http_request` in a subject?

2019-03-12 13:59 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +      it 'doesn\'t create a new book suggestion' do
```suggestion
      it "doesn't create a new book suggestion" do
```

2019-03-12 13:59 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        expect(response).to have_http_status(:unprocessable_entity)
If you want, a good exercise is to put this in a share_example. Because we standardize error, we can standardize test ;)

2019-03-12 15:07 UTC, Gmarn reviewed
And the 3rd context?

2019-03-12 15:07 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        post :create, params: { book_suggestion: book_suggestion }
Hum, why you do not use you subject here?

2019-03-12 15:07 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +    subject { post :create, params: { book_suggestion: book_suggestion } }
Name your subject, for example `http_request`

2019-03-12 15:07 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +    let!(:book_suggestion) { attributes_for(:book_suggestion) }
You do not need the `!`

2019-03-12 16:39 UTC, nicozar95 approved these changes

2019-03-12 17:10 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +RSpec.describe Api::V1::BookSuggestionsController, type: :controller do
```suggestion
describe Api::V1::BookSuggestionsController, type: :controller do
```

2019-03-12 17:10 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +  end
Can we add a context `When request params are invalid` and return 400

2019-03-12 18:51 UTC, Gmarn commented on spec/controllers/api/v1/book_suggestions_controller_spec.rb
> +        expect(response).to have_http_status(:bad_request)
This response where did come from? The before on the include example? Hum 🤔

2019-03-12 18:51 UTC, Gmarn commented on spec/support/shared_examples/error_examples.rb
> +    expect { http_request }.to change { BookSuggestion.count }.by(0)
You are doing 2 times the http_request in the before and here...

2019-03-13 14:42 UTC, Gmarn approved these changes

2019-03-13 17:12 UTC, Gmarn approved these changes

2019-03-13 18:37 UTC, merged