Add tests for Book model
wolox-training/sd-rails pull request #6
Opened 2019-03-05 14:16 UTC by sebasdeldi

## Summary
- Adds rspec, shoulda-matchers, factory-bot, database-cleaner and faker
- Adds unit tests for book model
- Allows travis cl to run rspec

## Trello Card
https://trello.com/c/LWzYrIPW/20-crear-tests-para-el-modelo-de-book

2019-03-06 12:16 UTC, nicozar95 requested changes

2019-03-06 12:16 UTC, nicozar95 commented on .travis.yml
>    # TODO allow rspec when installed and configured
Remove the TODO

2019-03-06 12:16 UTC, nicozar95 commented on spec/factories.rb
> +    genre { 'Horror' }
Use [Faker](https://github.com/stympy/faker) to create the factory so it doesn't use the same values always

2019-03-06 12:16 UTC, nicozar95 commented on spec/models/book_spec.rb
> +  subject(:book) { build(:book) }
`create(:book)` I know it's not a very huge change but it's preferable to test the model once it's created in the DB

2019-03-06 19:55 UTC, Gmarn commented on Gemfile
> +  gem 'database_cleaner'
Try to lock gem version, even in test ;)

2019-03-06 19:55 UTC, Gmarn commented on spec/factories.rb
> +    image { Faker::Book.title }
```suggestion
    image { Faker::Internet.url }
```

2019-03-07 12:31 UTC, nicozar95 approved these changes

2019-03-07 12:58 UTC, merged